
export const NEXT_PUBLIC_API_URL = "http://localhost:9000"
export const NEXT_PUBLIC_API_KEY = ""
export const NEXT_PUBLIC_VENDOR_ID = "vendor_01JDHBPFEBM0NZJHNMZHN55XAG"
export const NEXT_STORE_NAME = "FB"
export const NEXT_PUBLIC_STORE_ID = "store_01JEADBKRRJQZA160CREH15VEA"
export const NEXT_PUBLIC_SALES_CHANNEL_ID = "sc_01JEADBD2EQPAA2BGX88Z0QEXV"
export const NEXT_PUBLIC_CURRENCY_CODE = "usd"
export const NEXT_PORT = "8003"
      