export const NEXT_PUBLIC_API_URL = "http://localhost:9000"
export const NEXT_PUBLIC_API_KEY = "undefined"
export const NEXT_PUBLIC_VENDOR_ID = "vendor_01JDHBPFEBM0NZJHNMZHN55XAG"
export const NEXT_STORE_NAME = "Custom-Tees"
export const NEXT_PUBLIC_STORE_ID = "store_01JD1CHD5SFN3R7XAFT6HC7Z1K"
export const NEXT_PUBLIC_SALES_CHANNEL_ID = "sc_01JD1CH6D6P7A0978B8SFZE964"
export const NEXT_PUBLIC_CURRENCY_CODE = "usd"
export const NEXT_PORT = "8002"