export const NEXT_PUBLIC_API_URL = "http://localhost:9000"
export const NEXT_PUBLIC_API_KEY = "undefined"
export const NEXT_PUBLIC_VENDOR_ID = "vendor_01JDPG6P3ZSYDRKEZFB1WAR6AE"
export const NEXT_STORE_NAME = "Custom-Tees"
export const NEXT_PUBLIC_STORE_ID = "store_01JDPGC05AH7R4AGJMREZPNHHG"
export const NEXT_PUBLIC_SALES_CHANNEL_ID = "sc_01JDPGB9N6J7ENJ0D2B7C3B6CK"
export const NEXT_PUBLIC_CURRENCY_CODE = "usd"
export const NEXT_PORT = "8002"